# 👨‍💻 GitLab CI/CD - Portfólio Sergio Sena
stages:
  - deploy
  - invalidate

variables:
  S3_BUCKET: "portfolio-sergio-sena"
  CLOUDFRONT_DISTRIBUTION_ID: "E2O2ZMEA7SGXZ4"

deploy_s3:
  stage: deploy
  image: amazon/aws-cli:latest
  script:
    - aws s3 sync public/ s3://$S3_BUCKET --exclude "*.md" --exclude ".git/*" --exclude "aws/*" --exclude "config/*" --delete
  only:
    - main

invalidate_cache:
  stage: invalidate
  image: amazon/aws-cli:latest
  script:
    - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
  only:
    - main