name: Deploy Portfolio to AWS

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        
    - name: Sync public files to S3
      run: |
        aws s3 sync public/ s3://portfolio-sergio-sena/public/ --delete --exclude "*.git*"
        
    - name: Sync src files to S3
      run: |
        aws s3 sync src/ s3://portfolio-sergio-sena/src/ --delete --exclude "*.git*"
        
    - name: Invalidate CloudFront cache
      run: |
        aws cloudfront create-invalidation --distribution-id E2O2ZMEA7SGXZ4 --paths "/*"
        
    - name: Deployment notification
      run: |
        echo "✅ Portfolio deployed successfully!"
        echo "🌐 URL: https://dev-cloud.sstechnologies-cloud.com"
        echo "📦 CloudFront: E2O2ZMEA7SGXZ4"
        echo "🪣 S3 Bucket: portfolio-sergio-sena"